### ISSUE TITLE
Question: would these additions fit?

### ISSUE THREAD

**Issue by wimh** [spladug/fileinput.rs#2]
Hi, I have been working on a [`MultifileReader`](https://github.com/wimh/coreutils/blob/od/src/od/multifilereader.rs) type which is very similar to your `FileInput`. The most important differences are:
- Error handling - it basically continues even if there is an error. 
- I added `Box<io::Read>` to the Source enum. In particular because that allows me to unit test behaviour in case of errors - like removing an usb stick while reading from it.

Would you be interested if I create a pull request which allows something similar? 
- The error handling could be defined using a strategy module, which defaults to the current behaviour. That should not break anything, but allows me to change it. See for example [buf_redux](https://github.com/abonander/buf_redux) if you don't understand what I mean.
- But adding `Box<io::Read>` to the Source enum could break things, as it will probably not possible any more to implement `Clone`.
- I did not check if it is really feasible, I don't want to check this if you are not going to merge it anyway.

So let me know what you think.

**Comment by spladug** [comment]
Hello! Sorry for the delayed response. I'm very open to these suggestions/improvements! 

I like the idea of making the error handling into a strategy so we can maintain previous behaviour but allow other options too.

With respect to `Box<io::Read>` I'm a little less sure on how to proceed. I do like the idea of getting testing on the error handling and the potential flexibility there, but I'm a little concerned about compatibility of the public `Source` enum. Maybe it'd be worthwhile to split the publicly visible `Source` enum from the one used internally? Then we'd avoid breaking compatibility there.

Thanks for your interest in this repo, please let me know what I can do to help with these additions/improvements.

**Comment by wimh** [comment]
Ok, in that case, instead of the `Box<io::Read>`, I think about it creating an abstraction for the `File::open(path)`. Maybe something like [System.IO.Abstractions](https://github.com/tathamoddie/System.IO.Abstractions), which is for c#. It is a bit more work, but looks like a better long term solution. I believe this can be done in Rust using a zero-cost abstraction.

What I will do is write some code, so we can discuss based on that. I will probably not start with this until Monday. 

edit: The next two weeks I am a bit busy, I will start with this afterwards.

**Comment by wimh** [comment]
Created #3, so further discussion can go there.

(Now that I understand better how `FileInput` is working, I realise I could probably also accomplish my goal using a wrapper around `FileInput`. But that would be a bit more fragile).
